### ISSUE TITLE
Resolve linting errors

### ISSUE THREAD

**Issue by debck** [publiclab/community-toolbox#274]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**
```
// install ESLint
$ npm i -g eslint

// navigate and run linter
$ cd community-toolbox && eslint --fix .

// format code to fix linting errors
// you can also add various configuration rules by running `eslint --init` which create .eslintrc file.
```
After the errors are fixed, proceed as specified below.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by debck** [comment]
@jywarren Can you please add appropriate FTO labels to this issue.

**Comment by arnoschutijzer** [comment]
Can I take this up? :)

**Comment by mats-codes** [comment]
Hey, can I possibly on the solution of this issue? :)

**Comment by Rishabh570** [comment]
Hi @debck, can we make it work by installing it as a dev-dependency? Also, please put the code changes in the DIFF markdown so that it becomes easy for anyone to follow the instructions regarding code updations in the project.

@arnoschutijzer please go ahead if you would like to contribute. If you are not able to work on this for now, @mats-codes can go ahead.

Thanks, everyone.

**Comment by arnoschutijzer** [comment]
Let's switch it around. If @mats-codes is still available for this issue he can go for it, if not I can take it up.

**Comment by mats-codes** [comment]
@arnoschutijzer go ahead, I'll get involved somewhere else then :)

**Comment by arnoschutijzer** [comment]
Alright, so I was working on adding a script to `package.json` and linting config based on `eslint:recommended`. (see [here](https://eslint.org/docs/rules/))

I'm just not sure which files to lint and if the recommended config is okay. :)

**Comment by ovpv** [comment]
is this issue claimed? can I try this?

**Comment by arnoschutijzer** [comment]
sure, go for it!

**Comment by ovpv** [comment]
Hello @arnoschutijzer @debck ,

I believe to have fixed all the linting errors as per the ESlint standard rules, but when i do npm run test, 3 tests are failing. Please guide me forward.

```
> community-toolbox@1.0.0 test /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/community-toolbox
> jest

 FAIL  spec/recentContribsUtil/freshFetch.spec.js
  ● freshFetch.js › makes a fresh call to the github API for contributors

    Couldn't fetch commits for plots2

      17 |             return response.json();
      18 |           } else {
    > 19 |             throw new Error(`Couldn't fetch commits for ${repo}`);
         |                   ^
      20 |           }
      21 |         })
      22 |         .then(function gotResponseJson (response) {

      at gotResponse (src/utils/recentContribsUtil/freshFetch.js:19:19)
          at async Promise.all (index 0)

 FAIL  spec/repoUtil/fetchRepoUtil.spec.js
  ● fetchRepoUtil.js › returns an array of repositories's names

    Couldn't fetch repositories :(

      14 |         return data.json();
      15 |       } else {
    > 16 |         throw new Error("Couldn't fetch repositories :(");
         |               ^
      17 |       }
      18 |     })
      19 |     .then(function mapToEachRepo (results) {

      at gotRepos (src/utils/repoUtil/fetchRepoUtil.js:16:15)

 FAIL  spec/staleIssuesUtil/staleIssuesUtil.spec.js
  ● staleIssuesUtil.js › fetches stale issues list

    Couldn't fetch issues

      37 |                 return data.json();
      38 |               } else {
    > 39 |                 throw new Error("Couldn't fetch issues");
         |                       ^
      40 |               }
      41 |             })
      42 |             .then(function (data) {

      at src/utils/staleIssuesUtil.js:39:23
          at async Promise.all (index 0)

 PASS  spec/contribsUtil/fetchRepoContribsUtil.spec.js
 PASS  spec/contribsUtil/main.spec.js
 PASS  spec/contribsUtil/storeAllContribsInDb.spec.js
 PASS  spec/recentContribsUtil/getContribsLastMonth.spec.js
 PASS  spec/contribsUtil/fetchRepoContribs.spec.js
 PASS  spec/contribsUtil/fetchAllRepoContribs.spec.js
 PASS  spec/recentContribsUtil/getContribsLastWeek.spec.js
 PASS  spec/recentContribsUtil/storeAllRecentContribsInDb.spec.js
 PASS  spec/recentContribsUtil/fetchRecentMonthContribs.spec.js
 PASS  spec/recentContribsUtil/queryTime.spec.js
 PASS  spec/recentContribsUtil/fetchAllRecentMonthContribs.spec.js
 PASS  spec/recentContribsUtil/withinMonthsOrNot.spec.js
 PASS  spec/recentContribsUtil/withinThisWeekOrNot.spec.js
 PASS  spec/recentContribsUtil/main.spec.js

Test Suites: 3 failed, 14 passed, 17 total
Tests:       3 failed, 21 passed, 24 total
Snapshots:   0 total
Time:        6.144s
Ran all test suites.
```

**Comment by ovpv** [comment]
@debck @Rishabh570 , Please review my PR and let me know if any more changes are needed.
