### ISSUE TITLE
Ability to display all issues with a given label for a whole organization

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#79]
I tried this embed link to show all `gci-candidate` issues across all `publiclab` projects, but got a 404 error for the GitHub API call:

https://code.publiclab.org/examples/embed.html#o=publiclab&r=all&l=gci-candidate

```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/issues/#list-issues-for-a-repository"
}
```

This would be nice so we can pool all `design` issues, all `gci-candidate` issues, across projects, and link to them. 

Oddly, we can do this by specifying the `first-timers-only` parameter `f` in the main index.html page: 

https://code.publiclab.org/#o=publiclab&r=all&f=gci-candidate

(docs here: https://github.com/publiclab/community-toolbox/#configuration)

So I think we may just need to make some tweaks to get this working.

**Comment by Rishabh570** [comment]
@jywarren I guess this issue is resolved in #70 already, as I tried to navigate to the URL you mentioned above, I got the expected result...

![screenshot from 2018-10-22 22-31-55](https://user-images.githubusercontent.com/25483260/47306558-67ab3e80-d64a-11e8-8d48-a2607ae3fdb4.png)

**Comment by jywarren** [comment]
Huh, weird! I see:

```js
community-toolbox.js:11512 Unhandled rejection StatusCodeError: 404 - [object Object]    at new StatusCodeError (https://code.publiclab.org/dist/community-toolbox.js:63719:15)    at Request.RP$callback [as _callback] (https://code.publiclab.org/dist/community-toolbox.js:63800:32)    at Request.self.callback (https://code.publiclab.org/dist/community-toolbox.js:65543:22)    at emitTwo (https://code.publiclab.org/dist/community-toolbox.js:31148:13)    at Request.emit (https://code.publiclab.org/dist/community-toolbox.js:31219:7)    at Request.<anonymous> (https://code.publiclab.org/dist/community-toolbox.js:66519:10)    at emitOne (https://code.publiclab.org/dist/community-toolbox.js:31138:13)    at Request.emit (https://code.publiclab.org/dist/community-toolbox.js:31216:7)    at exports.IncomingMessage.<anonymous> (https://code.publiclab.org/dist/community-toolbox.js:66441:12)    at Object.onceWrapper (https://code.publiclab.org/dist/community-toolbox.js:31319:30)    at emitNone (https://code.publiclab.org/dist/community-toolbox.js:31133:20)    at exports.IncomingMessage.emit (https://code.publiclab.org/dist/community-toolbox.js:31213:7)    at endReadableNT (https://code.publiclab.org/dist/community-toolbox.js:62592:12)    at afterTickTwo (https://code.publiclab.org/dist/community-toolbox.js:59159:10)    at Item.run (https://code.publiclab.org/dist/community-toolbox.js:59332:14)    at drainQueue (https://code.publiclab.org/dist/community-toolbox.js:59302:42)
warn @ community-toolbox.js:11512
CapturedTrace.formatAndLogError @ community-toolbox.js:11220
CapturedTrace.fireRejectionEvent @ community-toolbox.js:11275
Promise._notifyUnhandledRejection @ community-toolbox.js:11668
Async._drainQueue @ community-toolbox.js:10739
Async._drainQueues @ community-toolbox.js:10746
Async.drainQueues @ community-toolbox.js:10626
setTimeout (async)
schedule @ community-toolbox.js:10690
Async._queueTick @ community-toolbox.js:10752
AsyncSettlePromises @ community-toolbox.js:10681
Async.settlePromises @ community-toolbox.js:10716
Promise._queueSettlePromises @ community-toolbox.js:13387
Promise._rejectUnchecked @ community-toolbox.js:13437
Promise._reject @ community-toolbox.js:13306
Promise._rejectCallback @ community-toolbox.js:13222
(anonymous) @ community-toolbox.js:13236
RP$callback @ community-toolbox.js:63800
self.callback @ community-toolbox.js:65543
emitTwo @ community-toolbox.js:31148
emit @ community-toolbox.js:31219
(anonymous) @ community-toolbox.js:66519
emitOne @ community-toolbox.js:31138
emit @ community-toolbox.js:31216
(anonymous) @ community-toolbox.js:66441
onceWrapper @ community-toolbox.js:31319
emitNone @ community-toolbox.js:31133
emit @ community-toolbox.js:31213
endReadableNT @ community-toolbox.js:62592
afterTickTwo @ community-toolbox.js:59159
Item.run @ community-toolbox.js:59332
drainQueue @ community-toolbox.js:59302
setTimeout (async)
runTimeout @ community-toolbox.js:59220
process.nextTick @ community-toolbox.js:59322
nextTick @ community-toolbox.js:59158
resume @ community-toolbox.js:62365
Readable.resume @ community-toolbox.js:62357
Readable.on @ community-toolbox.js:62327
Request.onRequestResponse @ community-toolbox.js:66430
emitOne @ community-toolbox.js:31138
emit @ community-toolbox.js:31216
ClientRequest._connect @ community-toolbox.js:75024
(anonymous) @ community-toolbox.js:74915
Promise.then (async)
ClientRequest._onFinish @ community-toolbox.js:74913
(anonymous) @ community-toolbox.js:74818
emitNone @ community-toolbox.js:31128
emit @ community-toolbox.js:31213
finishMaybe @ community-toolbox.js:63449
endWritable @ community-toolbox.js:63457
Writable.end @ community-toolbox.js:63413
ClientRequest.end @ community-toolbox.js:75053
Request.end @ community-toolbox.js:66872
end @ community-toolbox.js:65922
(anonymous) @ community-toolbox.js:65936
onNextTick @ community-toolbox.js:75379
Item.run @ community-toolbox.js:59332
drainQueue @ community-toolbox.js:59302
setTimeout (async)
runTimeout @ community-toolbox.js:59220
process.nextTick @ community-toolbox.js:59322
exports.setImmediate @ community-toolbox.js:75372
Request.init @ community-toolbox.js:65881
RP$initInterceptor @ community-toolbox.js:63855
Request @ community-toolbox.js:65485
request @ community-toolbox.js:63944
GithubService.(anonymous function).(anonymous function) @ community-toolbox.js:32321
(anonymous) @ embed.html:44
(anonymous) @ embed.html:51
```

**Comment by Rishabh570** [comment]
@jywarren It is working fine when I open it, 

![screenshot from 2018-10-23 08-11-45](https://user-images.githubusercontent.com/25483260/47331997-9271b300-d69b-11e8-95d9-6263b2fa8570.png)


Are you still getting that error?

**Comment by jywarren** [comment]
Nope, i see it now. Odd. But it doesn't seem like all the issues -- is it just 20 of them? That'd be OK, just checking!

**Comment by jywarren** [comment]
Ah, but I believe there should be over 87, as there are that many even just
on the plots2 repository. I would guess they're paginated... and this may
run us up against limits again, probably? I guess there's not too much we
can do about that...

https://github.com/publiclab/plots2/labels/gci-candidate

**Comment by Rishabh570** [comment]
I'll take a look into it, currently working on making month's contributors
to show up against queries through URL...

**Comment by jywarren** [comment]
No rush! Just documenting! And as more people become familiar with the code
perhaps someone else will take this up. :-)
